.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH ADANAXISRENDERINGDEMO 6 "August 2006" Linux "User Manuals"
.SH NAME
adanaxisrenderingdemo\-recover \- demonstration of the Adanaxis rendering system
.SH SYNOPSIS
.B adanaxisrenderingdemo\-recover
.SH DESCRIPTION
This command runs Adanaxis Rendering Demo in recovery mode, i.e. using safe
settings.  It is used when, for example, a display mode has been
saved in the configuarition that the monitor cannot display.
Documentation for this commands can be found in the
About Adanaxis Rendering Demo PDF, which is installed in the
documentation area (usually /usr/share/doc/adanaxisrenderingdemo-<version>)
.SH AUTHOR
Andy Southgate <andy.southgate@mushware.com>
.SH "SEE ALSO"
.BR adanaxisrenderingdemo (6)


