.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH ADANAXISRENDERINGDEMO 6 "August 2006" Linux "User Manuals"
.SH NAME
adanaxisrenderingdemo \- demonstration of the adanaxis rendering system
.SH SYNOPSIS
.B adanaxisrenderingdemo [commands]
.SH DESCRIPTION
Documentation for this command can be found in the
About Adanaxis Rendering Demo PDF, which is installed in the
documentation area (usually /usr/share/doc/adanaxisrenderingdemo-<version>)
.SH AUTHOR
Andy Southgate <andy.southgate@mushware.com>
.SH "SEE ALSO"
.BR adanaxisrenderingdemo\-recover (6)


