.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH ADANAXISCONTROLDEMO 6 "JUNE 2005" Linux "User Manuals"
.SH NAME
adanaxiscontroldemo\-recover \- demonstration of the Adanaxis control system
.SH SYNOPSIS
.B adanaxiscontroldemo\-recover
.SH DESCRIPTION
This command runs Adanaxis Control Demo in recovery mode, i.e. using safe
settings.  It is used when, for example, a display mode has been
saved in the configuarition that the monitor cannot display.
Documentation for this commands can be found in the
About Adanaxis Control Demo PDF, which is installed in the
documentation area (usually /usr/share/doc/adanaxiscontroldemo-<version>)
.SH AUTHOR
Andy Southgate <andy.southgate@mushware.com>
.SH "SEE ALSO"
.BR adanaxiscontroldemo (6)


