.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH TESSERACTTRAINER 6 "JUNE 2005" Linux "User Manuals"
.SH NAME
tesseracttrainer \- application for viewing a 4D tesseract
.SH SYNOPSIS
.B tesseracttrainer [commands]
.SH DESCRIPTION
Documentation for this commands can be found in the
About Tesseract Trainer PDF, which is installed in the
documentation area (usually /usr/share/doc/tesseracttrainer-<version>)
.SH AUTHOR
Andy Southgate <andy.southgate@mushware.com>
.SH "SEE ALSO"
.BR tesseracttrainer\-recover (6)


