.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH TESSERACTTRAINER 6 "JUNE 2005" Linux "User Manuals"
.SH NAME
tesseracttrainer\-recover \- application for viewing a 4D tesseract
.SH SYNOPSIS
.B tesseracttrainer\-recover
.SH DESCRIPTION
This command runs Tesseract Trainer in recovery mode, i.e. using safe
settings.  It is used when, for example, a display mode has been
saved in the configuarition that the monitor cannot display.
Documentation for this commands can be found in the
About Tesseract Trainer PDF, which is installed in the
documentation area (usually /usr/share/doc/tesseracttrainer-<version>)
.SH AUTHOR
Andy Southgate <andy.southgate@mushware.com>
.SH "SEE ALSO"
.BR tesseracttrainer (6)


